springdoc:
  swagger-ui:
    path: /

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:${db.port}/${db.dbname}
    username: ${db.username}
    password: ${db.password}

  elasticsearch:
    rest:
      uris: http://localhost:9200
      username: "elastic"
      password: "elastic"

  config:
    import: "classpath:API-KEY.yml"

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy:
          org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

  redis:  # Redis 설정을 spring.redis로 변경
    data:
      host: ${redis.data.host}
      port: ${redis.data.port}

kakao:
  client_id:
    rest_api_key: ${kakao.client_id.rest_api_key}
  redirect_uri: ${kakao.redirect_uri}

token:
  secret: ${token.secret}
  access_token_expiration_time: ${token.access_token_expiration_time}
  refresh_token_expiration_time: ${token.refresh_token_expiration_time}

cloud:
  aws:
    s3:
      bucket: ${s3.bucket}
    stack.auto: false
    region.static: ap-southeast-2
    credentials:
      accessKey: ${im.access}
      secretKey: ${im.secret}